// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://te-chun-liu.github.io',
  base: '/mmt-teaching-notes',
  trailingSlash: 'ignore',
  redirects: {
    '/day1/01-opening': '/mmt-teaching-notes/01-mmt-intro/00-opening-hooks',
    '/day1/02-foundation': '/mmt-teaching-notes/01-mmt-intro/02-academic-roots',
    '/day1/03-five-cores': '/mmt-teaching-notes/02-core-map/01-five-cores',
    '/day1/04-wind': '/mmt-teaching-notes/03-four-energies/01-wind',
    '/day1/05-fire': '/mmt-teaching-notes/03-four-energies/02-fire',
    '/day1/06-water': '/mmt-teaching-notes/03-four-energies/03-water',
    '/day1/07-earth': '/mmt-teaching-notes/03-four-energies/04-earth',
    '/day1-live/01-opening-culture': '/mmt-teaching-notes/01-mmt-intro/01-what-is-mmt',
    '/day1-live/02-conscious-layers': '/mmt-teaching-notes/02-core-map/02-conscious-layers',
    '/day1-live/03-special-charts': '/mmt-teaching-notes/04-special-charts/01-overview',
    '/day1-live/04-zero-energy': '/mmt-teaching-notes/05-zero-energy/01-detail',
    '/day1-live/05-energy-mastery': '/mmt-teaching-notes/06-energy-mastery/01-business',
    '/day1-live/06-team-three-stages': '/mmt-teaching-notes/17-team-stages/01-three-stages',
    '/day1-live/07-myth-architecture': '/mmt-teaching-notes/07-myth-foundation/01-architecture',
    '/day2/01-mythology': '/mmt-teaching-notes/08-22-cards-tree/01-mythology-tree',
    '/day2/02-wind-cards': '/mmt-teaching-notes/09-wind-cards/01-cards',
    '/day2/03-fire-cards': '/mmt-teaching-notes/10-fire-cards/01-cards',
    '/day2/04-water-cards': '/mmt-teaching-notes/11-water-cards/01-cards',
    '/day2/05-earth-cards': '/mmt-teaching-notes/12-earth-cards/01-cards',
    '/day2/06-closing': '/mmt-teaching-notes/18-year-strategy/02-closing',
    '/day2-live/01-water-behavior-industries': '/mmt-teaching-notes/13-behavior-modes/01-detail',
    '/day2-live/02-wealth-modes': '/mmt-teaching-notes/16-wealth-modes/01-five-modes',
    '/day2-live/03-mentor-shadow': '/mmt-teaching-notes/14-mentor-shadow/01-overview',
    '/day2-live/04-mentor-types': '/mmt-teaching-notes/14-mentor-shadow/02-types',
    '/day2-live/05-twelve-mentor-blocks': '/mmt-teaching-notes/15-mentor-blocks/01-detail',
    '/day2-live/06-year-strategy-closing': '/mmt-teaching-notes/18-year-strategy/01-detail',
    '/appendix/01-checklist': '/mmt-teaching-notes/19-appendix/01-checklist',
    '/appendix/02-followup': '/mmt-teaching-notes/19-appendix/02-followup',
    '/appendix/03-card-quick-ref': '/mmt-teaching-notes/19-appendix/03-card-quick-ref',
    '/appendix/04-survey': '/mmt-teaching-notes/19-appendix/04-survey',
    '/appendix/05-interview-questions': '/mmt-teaching-notes/19-appendix/05-interview-questions',
  },
  integrations: [
    starlight({
      title: '人生策略筆記本',
      description: '個人 MMT 主筆記本 ── 主題式整理，含投影片教案與課堂實錄整合',
      defaultLocale: 'root',
      locales: {
        root: { label: '繁體中文', lang: 'zh-TW' },
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/TE-CHUN-LIU/mmt-teaching-notes',
        },
      ],
      sidebar: [
        { label: '首頁', link: '/' },
        { label: '1 · MMT 概論', items: [{ autogenerate: { directory: '01-mmt-intro' } }] },
        { label: '2 · 五大核心地圖', items: [{ autogenerate: { directory: '02-core-map' } }] },
        { label: '3 · 四大能量', items: [{ autogenerate: { directory: '03-four-energies' } }] },
        { label: '4 · 特殊盤', items: [{ autogenerate: { directory: '04-special-charts' } }] },
        { label: '5 · 零能量者', items: [{ autogenerate: { directory: '05-zero-energy' } }] },
        { label: '6 · 能量精通商業帶人', items: [{ autogenerate: { directory: '06-energy-mastery' } }] },
        { label: '7 · 希臘神話架構', items: [{ autogenerate: { directory: '07-myth-foundation' } }] },
        { label: '8 · 22 張牌族譜', items: [{ autogenerate: { directory: '08-22-cards-tree' } }] },
        { label: '9 · 風能量 6 張牌', items: [{ autogenerate: { directory: '09-wind-cards' } }] },
        { label: '10 · 火能量 5 張牌', items: [{ autogenerate: { directory: '10-fire-cards' } }] },
        { label: '11 · 水能量 6 張牌', items: [{ autogenerate: { directory: '11-water-cards' } }] },
        { label: '12 · 土能量 5 張牌', items: [{ autogenerate: { directory: '12-earth-cards' } }] },
        { label: '13 · 行為模式', items: [{ autogenerate: { directory: '13-behavior-modes' } }] },
        { label: '14 · 導師與陰影', items: [{ autogenerate: { directory: '14-mentor-shadow' } }] },
        { label: '15 · 12 導師卡點', items: [{ autogenerate: { directory: '15-mentor-blocks' } }] },
        { label: '16 · 五種財富模式', items: [{ autogenerate: { directory: '16-wealth-modes' } }] },
        { label: '17 · 團隊三部曲', items: [{ autogenerate: { directory: '17-team-stages' } }] },
        { label: '18 · 流年與年度策略', items: [{ autogenerate: { directory: '18-year-strategy' } }] },
        { label: '19 · 速查表與附錄', items: [{ autogenerate: { directory: '19-appendix' } }] },
      ],
      customCss: ['./src/styles/brand.css'],
      lastUpdated: true,
    }),
  ],
});
